---
- name: Install and start Apache HTTP Server
  hosts: all
  become: yes
  tasks:
    - name: install apache2 httpd
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: apache2 service is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes

...
