- name: Implementing playscope variables
  hosts: all
  become: yes
  vars:
    a: tomcat10
    b: present
    c: yes
  tasks:
    - name: install s/w apps
      apt:
        name: "{{ a }}"
        state: "{{ b }}"
        update_cache: "{{ c }}"


