---
- name: Implementing  loops
  hosts: all
  tasks:
    - name: Install,uninstall of s/w apps 
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tree,b: present,c: no}
        - {a: openjdk-17-jdk,b: absent,c: no}
        - {a: maven,b: latest,c: yes}
...
