---
- name: Error Handling or Exception Handling in anible
  hosts: all
  tasks:
    - block:
       - name: Install git on Ubuntu servers
         apt:
           name: git
           state: present
           update_cache: yes
      rescue:
        - name: Install git on Redhat servers
          yum:
            name: git
            state: present
            update_cache: yes
      always:
        - name: Display output
          debug:
            msg: "Git installtion done"
