---
- name: configuring tomcat
  hosts: all
  tasks:
    - name: Install tomcat10
      apt:
        name: tomcat10
        state: present
        update_cache: yes
    - name: Install tomcat10-admin
      apt:
        name: tomcat10-admin
        state: present
        update_cache: yes
    - name: copy customised tomcat-user.xml file
      copy:
        src: tomcat-user.xml
        dest: /etc/tomcat10
    - name: change port of tomcat on 8080 to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: restart tomcat
      service:
        name: tomcat10
        state: restarted
    - name: pause for 60 sec
      pause:
        seconds: 60
    - name: check tomcat on server1
      uri:
        url: http://172.31.95.231:9090
        status_code: 200
    - name: check tomcat on server2
      uri:
        url: http://172.31.87.110:9090
        status_code: 200

...
