---
- name: Capture Os info
  hosts: all
  tasks:
    - name: Capture OS name
      debug:
        var: "{{ansible_distribution}}"
    - name: Capture Os version info
      debug:
        var: "{{ansible_distribution_version}}"
    - name: Capture OS major version no
      debug:
        var: "{{ansible_distribution_major_version}}"
...
